from __future__ import annotations

import json
from pathlib import Path

from quantresearch_api.main import create_app

ROOT = Path(__file__).resolve().parents[1]
GENERATED_DIR = ROOT / "apps" / "web" / "src" / "generated"
OPENAPI_PATH = GENERATED_DIR / "openapi.json"
CLIENT_PATH = GENERATED_DIR / "apiClient.ts"


CLIENT_SOURCE = """/* eslint-disable */
// Generated by tools/generate_openapi_client.py. Do not edit by hand.

export type SectionKey =
  | "data"
  | "experiments"
  | "strategies"
  | "portfolios"
  | "risk"
  | "audit"
  | "users";

export type ConsoleMetric = {
  key: SectionKey;
  label: string;
  value: string;
  detail: string;
};

export type ConsolePanel = {
  key: SectionKey;
  title: string;
  description: string;
  action: string;
  rows: Array<Record<string, string>>;
};

export type ConsoleResponse = {
  metrics: ConsoleMetric[];
  panels: ConsolePanel[];
  workspace_name: string;
  verification_state: string;
};

export type ApiClientOptions = {
  baseUrl?: string;
  headers?: Record<string, string>;
};

const defaultBaseUrl = import.meta.env.VITE_API_BASE_URL ?? "http://127.0.0.1:8000";

export async function getConsole(
  options: ApiClientOptions = {},
  signal?: AbortSignal
): Promise<ConsoleResponse> {
  const response = await fetch(`${options.baseUrl ?? defaultBaseUrl}/api/v1/console`, {
    headers: {
      "x-role": "platform_admin",
      ...options.headers
    },
    signal
  });

  if (!response.ok) {
    throw new Error(`Console API returned ${response.status}`);
  }

  return response.json() as Promise<ConsoleResponse>;
}
"""


def main() -> None:
    GENERATED_DIR.mkdir(parents=True, exist_ok=True)
    openapi = create_app().openapi()
    OPENAPI_PATH.write_text(json.dumps(openapi, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    CLIENT_PATH.write_text(CLIENT_SOURCE, encoding="utf-8")


if __name__ == "__main__":
    main()
